### PR TITLE
Bugfix/cart update

### PR DESCRIPTION
**Pull request by mendesalan**
- This Update catch product ID instead of product sku
- updated url links

### CODE REVIEW

**Comment by gris** [comment]
Thanks for the contribution @mendesalan ! Can you please provide a link and instructions with a running workspace so that we can test the modifications? Thanks!

**Comment by mendesalan** [comment]
@joaomarcosgris 
workspace: https://rtbhouse--acupula.myvtex.com/
How to test:
1. open your network and filter by the word: creative
 which is the URL being created on iframe.
These are the events:
vtex:pageInfo
vtex:productView
vtex:internalSiteSearchView
vtex:categoryView
vtex:departmentView
vtex:orderPlaced

**Comment by gris** [comment]
Thank you! It seems that there are some breaking changes here right? What do you think?

**Comment by mendesalan** [comment]
> Thank you! It seems that there are some breaking changes here right? What do you think?

Hi @joaomarcosgris, what do you mean by breaking changes?
Me and the RTB-HOUSE team have tested and everything seems ok.

Let me know your feedback!

Thanks!

**Comment by gris** [comment]
@mendesalan what I mean by breaking changes is knowing if we make these changes we would broke some accounts that are already using it. So we would have to publish it as a major. Otherwise, our continuous delivery bot, Housekeeper would update the app in every account that it is installed.

**Comment by mendesalan** [comment]
> @mendesalan what I mean by breaking changes is knowing if we make these changes we would broke some accounts that are already using it. So we would have to publish it as a major. Otherwise, our continuous delivery bot, Housekeeper would update the app in every account that it is installed.

Oh i see!
That's no problem at all.
We definitely should proceed this way.

For me is all ok.

When can we expect this change to be published @joaomarcosgris ?

Thanks!

**Comment by gris** [comment]
Hey @mendesalan sorry for the waiting. I don't have write rights for this repo. @saviofelixmuniz can you please merge it after selecting as a major, please?

**Review by saviomuniz — APPROVED** [review]

**Pull request merged**
